name: Build and Push Kathara Pc2 Image

on:
  push:
    paths:
      - docker/pc2/Dockerfile
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build-and-push-image:
    permissions:
      packages: write
      contents: read
    name: Build and Push Kathara Pc2 Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: docker/pc2/Dockerfile
          push: true
          tags: ghcr.io/ireproces/pc2:latest